version: "3.9"

networks:
  web:
    driver: bridge
    name: dolibarr-web

volumes:
  db16_data:
  db17_data:
  db18_data:
  db19_data:
  db20_data:
  db21_data:
  db22_data:

services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  dashboard:
    image: nginx:alpine
    depends_on:
      - traefik
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
      - ./dashboard/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dylan.local`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.services.dashboard.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db16:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr16
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db16_data:/var/lib/mysql
    networks:
      - web

  dolibarr16:
    image: tuxgasy/dolibarr:16
    depends_on:
      - db16
    environment:
      DOLI_DB_HOST: db16
      DOLI_DB_NAME: dolibarr16
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr16.local
    volumes:
      - ./instances/dolibarr-16:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr16.rule=Host(`dolibarr16.local`)
      - traefik.http.routers.dolibarr16.entrypoints=web
      - traefik.http.services.dolibarr16.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db17:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr17
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db17_data:/var/lib/mysql
    networks:
      - web

  dolibarr17:
    image: tuxgasy/dolibarr:17
    depends_on:
      - db17
    environment:
      DOLI_DB_HOST: db17
      DOLI_DB_NAME: dolibarr17
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr17.local
    volumes:
      - ./instances/dolibarr-17:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr17.rule=Host(`dolibarr17.local`)
      - traefik.http.routers.dolibarr17.entrypoints=web
      - traefik.http.services.dolibarr17.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db18:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr18
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db18_data:/var/lib/mysql
    networks:
      - web

  dolibarr18:
    image: tuxgasy/dolibarr:18
    depends_on:
      - db18
    environment:
      DOLI_DB_HOST: db18
      DOLI_DB_NAME: dolibarr18
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr18.local
    volumes:
      - ./instances/dolibarr-18:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr18.rule=Host(`dolibarr18.local`)
      - traefik.http.routers.dolibarr18.entrypoints=web
      - traefik.http.services.dolibarr18.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db19:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr19
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db19_data:/var/lib/mysql
    networks:
      - web

  dolibarr19:
    image: tuxgasy/dolibarr:19
    depends_on:
      - db19
    environment:
      DOLI_DB_HOST: db19
      DOLI_DB_NAME: dolibarr19
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr19.local
    volumes:
      - ./instances/dolibarr-19:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr19.rule=Host(`dolibarr19.local`)
      - traefik.http.routers.dolibarr19.entrypoints=web
      - traefik.http.services.dolibarr19.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db20:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr20
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db20_data:/var/lib/mysql
    networks:
      - web

  dolibarr20:
    image: tuxgasy/dolibarr:20
    depends_on:
      - db20
    environment:
      DOLI_DB_HOST: db20
      DOLI_DB_NAME: dolibarr20
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr20.local
    volumes:
      - ./instances/dolibarr-20:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr20.rule=Host(`dolibarr20.local`)
      - traefik.http.routers.dolibarr20.entrypoints=web
      - traefik.http.services.dolibarr20.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db21:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr21
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db21_data:/var/lib/mysql
    networks:
      - web

  dolibarr21:
    image: tuxgasy/dolibarr:21
    depends_on:
      - db21
    environment:
      DOLI_DB_HOST: db21
      DOLI_DB_NAME: dolibarr21
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr21.local
    volumes:
      - ./instances/dolibarr-21:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr21.rule=Host(`dolibarr21.local`)
      - traefik.http.routers.dolibarr21.entrypoints=web
      - traefik.http.services.dolibarr21.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web

  db22:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: dolibarr22
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db22_data:/var/lib/mysql
    networks:
      - web

  dolibarr22:
    image: tuxgasy/dolibarr:22
    depends_on:
      - db22
    environment:
      DOLI_DB_HOST: db22
      DOLI_DB_NAME: dolibarr22
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      DOLI_URL_ROOT: http://dolibarr22.local
    volumes:
      - ./instances/dolibarr-22:/var/www/html:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr22.rule=Host(`dolibarr22.local`)
      - traefik.http.routers.dolibarr22.entrypoints=web
      - traefik.http.services.dolibarr22.loadbalancer.server.port=80
      - traefik.docker.network=dolibarr-web
    networks:
      - web
